title: My Research
description: Papers, datasets, and project pages
url: "https://andrei044.github.io"
baseurl: ""
permalink: /:categories/:title/

# Collections for articles
collections:
  articles:
    output: true
    permalink: /articles/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: article

# Build
markdown: kramdown
theme: null
plugins: []   # keep empty; works with GitHub Pages default